### ISSUE TITLE
How to get recently included device and inclusion mode problems 

### ISSUE THREAD

**Issue by phanindra466** [roblans/ZWave4Net#25]
We are developing z-wave network with Aeotec z-stick gen5 and multisensor6 (ZW100)
And quad wall mote controller.
 
1.	I want to  capture newly  added device in network.is there any way that I can get newly added device from z-stick or is there any event handler that acting on inclusion  and exclusion ?
2.	Now  I am removing Z-stick from raspberry pi to include device into network. I want to place z-stick in inclusion through code.is there any way that I can place z-stick in inclusion mode without removing it  from raspberry pi?
3.	How to know the device connected to network is available for operations or not available for operations?

thanks in advance.

**Comment by roblans** [comment]
Hi,

1. No, there is no event handler that is acting on inclusion and exclusion. Inclusion or Exclusion is not (yet) supported by ZWave4Net.
2. No, not from code

3. Call node.GetProtocolInfo(), use the IsListening property. This will return true if the device available for operations (non-battery devices)

`                var protocolInfo = await node.GetProtocolInfo();
                Console.WriteLine(protocolInfo.IsListening);
`

For battery devices use the WakeUp CommandClass, this class will fire a Changed event when the node is Awake and ready for operations.

**Comment by phanindra466** [comment]
Hi

Thanks for response.I have few confusions in particular scenarios

-----No, there is no event handler that is acting on inclusion and exclusion. Inclusion or Exclusion is not (yet) supported by ZWave4Net

1.if there is no event handler acting on it how can I get recent included device?


-----No, not from code

2.If we remove zstick from Raspberry pi  can it communicate to my raspberry pi through wireless channel?

**Comment by roblans** [comment]
Hi,

Let's make things clear: inclusion of nodes only has to be done once. The z-stick remembers the association.

So, what you need to do is:
- Remove the z-stick from the raspberry pi
- Set the device in inclusion mode (see manual) and press the inclusion button on the z-stick
- When successful the z-stick  and the device are associated, the z-stick remembers the node (even when not connected to the raspberry pi)
- Put the stick into the raspberry pi and start programming

**Comment by yamunakonda** [comment]
Hi,
1. How can we know the controller status whether it is in offline or online through code ?
2. How can we know when a zstick is included in raspberry pi through code ?
3. Is there any way to identify a controller uniquely when there are multiple controllers through code ?

Thanks in advance...

**Comment by phanindra466** [comment]
Hi,
  To start programming after placing raspberry pi,**can I know whether user placed z-stick or any other 
 device type ?**
1. is there any static properties for controller that can access without opening controller?

> I had found homeID Unique for z-stick but it can be accessible only after opening controller so need property that can be unique while start programming on z-stick

**Comment by phanindra466** [comment]
Hi,

I had got GetProtocolInfo().Islistening value for USB powered device as true.but device is not connected to power.
  i had read in library that
3. **Call node.GetProtocolInfo(), use the IsListening property. This will return true if the device available for operations (non-battery devices)
var protocolInfo = await node.GetProtocolInfo(); Console.WriteLine(protocolInfo.IsListening);**

it is not accurate as per device.
- Is there any way that i can  get accurate readings from device?

Thanks for your Help
