### ISSUE TITLE
Can't get Active Power from a device

### ISSUE THREAD

**Issue by rlcx** [roblans/ZWave4Net#26]
Hi,

I am using a Single Switch from Fibaro (FGS-213). Datasheet available here : https://manuals.fibaro.com/content/manuals/en/FGS-2x3/FGS-2x3-EN-T-v1.0.pdf

According to page 12, you can get two types of values for power consumption.
 - Electric active power
 - Electric energy

When using Metter CommandClass, I can get Electric energy (in kWh) but I don't find how to get Electric active power value.

```cs
var controller = new ZWaveController("COM4");
controller.Open();
var nodes = await controller.GetNodes();
var node = nodes[(byte)2];
var meter = node.GetCommandClass<Meter>();
var meterGet = await meter.Get();

var value = meterGet.Value; // Something like 1,03
var unit = meterGet.Unit; // kWh
```

Are there other ways to get meter values from the Metter Command class ?
Maybe a way to get other Meters from the same device ?

Thanks for your help.

**Comment by roblans** [comment]
Hi, 

Try to get the power value by using the SensorMultiLevel class

`  
var sensorMultiLevel = node.GetCommandClass<SensorMultiLevel>();
var powerValue = sensorMultiLevel.Get(SensorType.Power);
var powerValue = sensorMultiLevel.Get(SensorType.Power);
`

**Comment by rlcx** [comment]
Thanks for your help @roblans !
It fails unfortunately.

It look like this device does not support SensorMultiLevel class. It is supporting the command classes listed on this page : https://products.z-wavealliance.org/products/1873/classes

 - Application Status
 - Association Group Information V1
 - Association V2
 - Basic V1
 - Binary Switch V1
 - Central Scene V2
 - Configuration V1
 - CRC16 Encapsulation
 - Device Reset Local V1
 - Firmware Update MD V3
 - Manufacturer Specific V2
 - Meter V3
 - Multi-Channel Association V3
 - Multi-Channel V4
 - Notification V5
 - Powerlevel
 - Protection V2
 - Security V1
 - Version V2
 - Z-Wave Plus Info V2

At first, I guessed it should be Powerlevel command class. I forked your repository and started to handle it but Powerlevel is about the powerlevel of the zwave signal, not the power consumption of the connected device.

It look like this information is hidden somewhere else but I don't get it.

**Comment by rlcx** [comment]
I tried the method `GetSupported()` from the `Meter` Command Class. It returns Electric as `Type` and an array with `kWh` and `W` as supported Units. It look like it should be possible to add a parameter to the Get of the meter value of the command class ?

```cs
var meter = node.GetCommandClass<Meter>();
var supported = await meter.GetSupported();
Console.WriteLine($"{supported .Type} - {string.Join(", ", supported .Units)}"); // Electric - kWh, W

var consumption = await meter.Get();
Console.WriteLine($"{consumption .Value} {consumption .Unit}"); // 3,02 kWh
```

**Comment by roblans** [comment]
Yes, you are right, I checked the Z-wave specification and there is an extra optional parameter which can be passed to the Get command. This parameter determines the type of metervalue to return.

I will fix this tomorrow.

Rob.

**Comment by roblans** [comment]
Done:

```
var meter = node.GetCommandClass<Meter>();
var value = await meter.Get(ElectricMeterScale.W);
```

New NuGet package (1.0.0.178) published.

**Comment by rlcx** [comment]
Working perfectly, thank you :)
