### ISSUE TITLE
aeotec multisensor battery problem

### ISSUE THREAD

**Issue by phanindra466** [roblans/ZWave4Net#30]
Hi,
I had multisensor 6 running on battery,the command class for multisensor has implemented batterydevice.
but when i try to get battery level from multisensor through **GetBatteryLevel()**.it is throwing transmission exception.How can i get battery level of device.

**Comment by roblans** [comment]
The batterylevel can only be retrieved when the sensor is awake. Subscribe to the 'WakeUp' event and invoke the GetBatteryLevel method:

`
            multiSensor6.WakeUp += async (s, e) =>
            {
                var batteryLevel = await multiSensor6.GetBatteryLevel();
            };
`
