### ISSUE TITLE
Problem with ZME_WALLC-S Wall Controller

### ISSUE THREAD

**Issue by fondencn** [roblans/ZWave4Net#34]
Using the following configuration
- AEOTEC ZStick Gen5 as static Controller
- ZME_WALLC-S (POPP Wall Controller)

causes the following Problem:

- I cannot receive Scene or CentralScene Events in this configuration, 
- The only noticable event is the Basic "MessageReceived" event, nothing more
- Neither the CentralScene nor the SceneActivation CommandClasses do work

Please note that the devices are included correctly, I cross-checked with the ZenSys Tools.

Plattform is .NetCore (3.0).

I'd appreciate any help or comments ;-)

Code Snipped (C#): 
```
                    var basic = node.GetCommandClass<Basic>();
                    basic.Changed += OnBasicChanged;

                    var scene = node.GetCommandClass<SceneActivation>();
                    scene.Changed += OnSceneChanged;

                    var centralScne = node.GetCommandClass<CentralScene>();
                    scene.Changed += OnCentralSceneChanged;
```

None of the delegates is called.

**Comment by roblans** [comment]
Use this code to enable logging
 
```
                var controller = new ZWaveController("COM1");
                controller.Channel.Log = Console.Out;

```

Press a button on the ZME_WALLC-S to see if any logmessages are receievd

**Comment by fondencn** [comment]
ok I'll give it a try...

**Comment by fondencn** [comment]
ok, seems like basically the Scene Controller is working, I can see the following log: 
```
2019-10-23 22:48:33.127 Received: SOF Response ApplicationCommandHandler TypeSingle, NodeID:011, Command:[Class:CentralScene, Command:3, Payload:FC-00-06]
2019-10-23 22:48:33.134 Transmitted: ACK  
```
But still the ``CentralScene`` command class' ``changed`` event is not fired at all. 

What can I do?

**Comment by roblans** [comment]
There is an error in your code snippet. The last line should be:

**centralScne**.Changed += OnCentralSceneChanged;

**Comment by fondencn** [comment]
OMG what a shame, you are so right!

Thanks for the hint, everything is working as expected now! I'll close the issue, sorry for the inconvenience...

**Comment by roblans** [comment]
No problem. I'm glad it's working now.

Regards, Rob.
