### ISSUE TITLE
.NET 5 System.ServiceModel dependency

### ISSUE THREAD

**Issue by Cypher87** [roblans/ZWave4Net#47]
I've published an application for .NET 5 using ZWave4Net (via NuGet). When running it throws the following exception:

"Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified."

It seems that the ControllerRestService/ZWaveRestServer uses System.ServiceModel. I do not need these webservice files in my project, so I have compiled ZWave4Net from source to remove this dependency.

**Comment by fondencn** [comment]
I believe we should seperate both packages into one for basic zwave functionality and one for the new REST server. 
This would be more practical as some of as (at least myself) have implemented their own network wrappers, thus not needing the new dependency on WCF.

**Comment by roblans** [comment]
I've removed the ZWaveRestServer code and the System.ServiceModel dependency (the code was meant for private use only).
