### ISSUE TITLE
VendorId and ProductId

### ISSUE THREAD

**Issue by bjthompson44** [roblans/ZWave4Net#6]
Hi, thank you for your work.  Where do we get the vendorId and productid indicated in "note: opening the serialport by name fails on Windows 10 IoT, use USB vendorId and productId" ?  Thanks!

**Comment by roblans** [comment]
0x0658 and 0x0200 are the correct values for the Aeon Labs Z-Stick. For other sticks use the windows device manager:

http://www.gilsmethod.com/how_to_resolve_unknown_device_problems
