### ISSUE TITLE
Latest version does not work anymore with Win/Linux Z-Stick Gen5

### ISSUE THREAD

**Issue by RicoSuter** [roblans/ZWave4Net#77]
The latest version always gives connection timeouts. 

The reason is this new code: 
https://github.com/RicoSuter/HomeBlaze/blob/main/src/HomeBlaze.Zwave/ZWave/Channel/ZWaveChannel.cs#L297C1-L297C1

I had to inline the whole library and fix this for now...
I dont know what this is useful for but in my case it breaks the whole thing. 

Would it be possible to either remove this, fix or make optional via parameter in the ZwaveController ctor?
Thank you very much

**Comment by roblans** [comment]
I've removed the soft reset code from the ZWaveChannel.Open method. Soft reset is now available by the new method ZWaveController.SoftReset. 

New NuGet package released: 1.3.1

**Comment by RicoSuter** [comment]
Can confirm it works again... thank you very much.
Ref: https://github.com/RicoSuter/HomeBlaze/commit/c433be9ac7aaf6234cb1fbc0307de516a7ee3e25
